### ISSUE TITLE
Correct semantic version number for GatorGradle

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/python-starter#4]
The current semantic version number for the GatorGrader plugin is not correct. It should currently be listed at `0.3.1` instead. Can someone look into this issue and make the needed change? Also, it would be a good idea if we developed an approach that automated these types of changes in the configuration for all of our sample assignments, especially given the fact that we are going to have more sample assignments in the future!

**Comment by Michionlion** [comment]
See [java-assignment-starter#3](https://github.com/GatorEducator/java-assigment-starter/issues/3) for discussion on automation!

**Comment by Michionlion** [comment]
Fixed by using a buildscript method.
